import React from 'react';

// Helper to get AI image
const getAiImage = (prompt, width=800, height=600) => {
  if (!prompt) return `https://picsum.photos/${width}/${height}`;
  return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=${width}&height=${height}&nologo=true`;
};

// Basic Placeholder Components
const Hero = ({ branding, props = {} }) => (
  <div style={{ backgroundColor: branding.colors.primary, color: branding.colors.text }} className="relative text-center rounded-lg my-4 overflow-hidden group">
    {props.imagePrompt && (
      <div className="absolute inset-0 z-0">
        <img src={getAiImage(props.imagePrompt, 1200, 600)} alt="Hero Background" className="w-full h-full object-cover opacity-30 group-hover:opacity-40 transition-opacity duration-700" />
      </div>
    )}
    <div className="relative z-10 py-24 px-8">
      <h1 className="text-5xl font-bold mb-6">{props.title || `Welcome to ${branding.theme} Theme`}</h1>
      <p className="text-xl max-w-2xl mx-auto opacity-90">{props.description || 'This is an AI generated Hero section. It uses your brand primary color.'}</p>
      <button className="mt-8 px-6 py-3 bg-white text-black font-semibold rounded-full hover:bg-gray-100 transition-colors">
        Get Started
      </button>
    </div>
  </div>
);

const Features = ({ branding, props = {} }) => (
  <div style={{ backgroundColor: branding.colors.background, color: branding.colors.text }} className="py-16 px-8 my-4">
    <h2 className="text-3xl font-bold text-center mb-12">{props.title || 'Core Features'}</h2>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
      {[1, 2, 3].map(i => (
        <div key={i} className="p-6 border rounded-xl overflow-hidden shadow-sm" style={{ borderColor: branding.colors.secondary }}>
          {props.imagePrompt && (
             <img src={getAiImage(props.imagePrompt + ' feature ' + i, 400, 250)} alt="Feature" className="w-full h-40 object-cover rounded mb-4" />
          )}
          <h3 className="text-xl font-semibold mb-2">Feature {i}</h3>
          <p className="opacity-80 text-sm">{props.description || 'Dynamic feature block generated by AI planner.'}</p>
        </div>
      ))}
    </div>
  </div>
);

const Testimonials = ({ branding, props = {} }) => (
  <div style={{ backgroundColor: branding.colors.background, color: branding.colors.text }} className="py-16 px-8 my-4 border-y" style={{ borderColor: branding.colors.accent }}>
    <h2 className="text-3xl font-bold text-center mb-12">{props.title || 'What Clients Say'}</h2>
    <div className="flex flex-wrap justify-center gap-6">
      <div className="p-6 bg-gray-50 dark:bg-gray-800 rounded-lg max-w-md shadow-sm">
        <p className="italic mb-4">"{props.description || 'This generated website structure looks amazing. The colors applied perfectly!'}"</p>
        <span className="font-semibold text-sm" style={{ color: branding.colors.primary }}>- Happy Customer</span>
      </div>
    </div>
  </div>
);

const Footer = ({ branding, props = {} }) => (
  <div style={{ backgroundColor: branding.colors.text, color: branding.colors.background }} className="py-12 px-8 mt-12 text-center text-sm rounded-t-xl">
    <h3 className="font-bold text-lg mb-2">{props.title || 'AI Website Builder'}</h3>
    <p>{props.description || '© 2026 All rights reserved.'}</p>
  </div>
);

const Contact = ({ branding, props = {} }) => (
  <div style={{ backgroundColor: branding.colors.background, color: branding.colors.text }} className="py-16 px-8 my-4">
    <div className="max-w-md mx-auto p-8 rounded-xl shadow-lg border" style={{ borderColor: branding.colors.accent }}>
      <h2 className="text-2xl font-bold mb-6 text-center">{props.title || 'Get in Touch'}</h2>
      <p className="text-center mb-6 opacity-80">{props.description || 'Leave us a message'}</p>
      <input type="text" placeholder="Name" className="w-full mb-4 p-3 rounded border bg-transparent" />
      <input type="email" placeholder="Email" className="w-full mb-4 p-3 rounded border bg-transparent" />
      <button className="w-full p-3 rounded font-bold text-white" style={{ backgroundColor: branding.colors.accent }}>Send Message</button>
    </div>
  </div>
);

const UnknownComponent = ({ type, branding, props = {} }) => (
  <div className="p-6 border-2 border-dashed border-gray-400 text-gray-500 text-center my-4 rounded-lg bg-gray-50 dark:bg-gray-800">
    <p>Component: <strong>{type}</strong></p>
    {props.title && <h3 className="text-xl font-bold mt-2 text-black dark:text-white">{props.title}</h3>}
    {props.description && <p className="mt-2 text-sm text-black dark:text-white opacity-80">{props.description}</p>}
    {props.imagePrompt && (
      <img src={getAiImage(props.imagePrompt, 600, 300)} alt={props.title} className="w-full h-48 object-cover rounded mt-4" />
    )}
  </div>
);

const componentMap = {
  'Hero': Hero,
  'Features': Features,
  'Testimonials': Testimonials,
  'Footer': Footer,
  'Contact': Contact
};

const LivePreview = ({ page, branding }) => {
  if (!page) return <div className="p-8 text-center text-gray-500">No page selected.</div>;

  const fontStyle = {
    fontFamily: branding?.fonts?.body || 'Inter, sans-serif',
    backgroundColor: branding?.colors?.background || '#ffffff',
    color: branding?.colors?.text || '#000000',
    minHeight: '100%',
  };

  return (
    <div style={fontStyle} className="rounded-lg shadow-2xl overflow-hidden transition-colors duration-500">
      {page.components && page.components.length > 0 ? (
        page.components.map((comp, idx) => {
          const Component = componentMap[comp.type] || UnknownComponent;
          return <Component key={comp._id || idx} type={comp.type} branding={branding} props={comp.props} />;
        })
      ) : (
        <div className="p-12 text-center opacity-60">
          <h2 className="text-2xl font-bold mb-2">{page.title}</h2>
          <p>No components generated for this page yet.</p>
        </div>
      )}
    </div>
  );
};

export default LivePreview;
